name: quizm_user_backend

services:
  web:
    build: .
    container_name: fastapi_app
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8888
      "
    ports:
      - "127.0.0.1:8888:8888"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: on-failure

  db:
    image: postgres:17
    container_name: pg_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh