"""'add_quiz_name'

Revision ID: 30c90bb0b02d
Revises: 0b95590bfe85
Create Date: 2025-04-11 19:13:30.242933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30c90bb0b02d"
down_revision: Union[str, None] = "0b95590bfe85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("quiz_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "quiz_name")
    # ### end Alembic commands ###
